[tool.poetry]
name = "alekorn-page-loader"
version = "0.1.0"
description = ""
authors = ["alekorn <entkorn@gmail.com>"]
packages = [
  { include = "page_loader" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
page-loader = "page_loader.scripts.page_loader:main"
